package A177_Enchanted.a177_added_modified_enchantments.init;

import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import A177_Enchanted.a177_added_modified_enchantments.A177_added_modified_enchantments;
import A177_Enchanted.a177_added_modified_enchantments.enchantments.*;

public class ModEnchantments {
    public static final DeferredRegister<Enchantment> ENCHANTMENTS =
            DeferredRegister.create(ForgeRegistries.ENCHANTMENTS, A177_added_modified_enchantments.MODID);

    public static final RegistryObject<Enchantment> STONE_PELLET_MAN = ENCHANTMENTS.register("stone_pellet_man", StonePelletManEnchantment::new);// 石粒人
    public static final RegistryObject<Enchantment> CRUSHING_FIST_CHESTPLATE = ENCHANTMENTS.register("crushing_fist_chestplate", CrushingFistChestplateEnchantment::new);//碎岩拳甲
    public static final RegistryObject<Enchantment> SPRING_FIST_CHESTPLATE = ENCHANTMENTS.register("spring_fist_chestplate", SpringFistChestplateEnchantment::new);//咏春拳甲
    public static final RegistryObject<Enchantment> DIAMOND_OBSIDIAN_FIST_CHESTPLATE = ENCHANTMENTS.register("diamond_obsidian_fist_chestplate", DiamondObsidianFistChestplateEnchantment::new);//钻耀拳甲
    public static final RegistryObject<Enchantment> FIST_PUNCH_CHESTPLATE = ENCHANTMENTS.register("fist_punch_chestplate", FistPunchChestplateEnchantment::new);//直拳拳甲
    public static final RegistryObject<Enchantment> BOXING_ARMOR = ENCHANTMENTS.register("boxing_armor", BoxingArmorEnchantment::new);//拳击甲胄
    public static final RegistryObject<Enchantment> SEVERE_INJURY_FIST = ENCHANTMENTS.register("severe_injury_fist", SevereInjuryFistEnchantment::new);//重伤拳甲
    public static final RegistryObject<Enchantment> BONE_BREAKER_FIST = ENCHANTMENTS.register("bone_breaker_fist", BoneBreakerFistEnchantment::new);//碎骨拳甲
    public static final RegistryObject<Enchantment> EMPTY_MIND_FIST = ENCHANTMENTS.register("empty_mind_fist", EmptyMindFistEnchantment::new);//空明拳甲
    public static final RegistryObject<Enchantment> FOCUSED_FIST = ENCHANTMENTS.register("focused_fist", FocusedFistEnchantment::new);//专注拳甲
    public static final RegistryObject<Enchantment> RED_RUSH_FIST = ENCHANTMENTS.register("red_rush_fist", RedRushFistEnchantment::new);//赤冲拳甲
    public static final RegistryObject<Enchantment> SLOW_HEAVY_BLOW = ENCHANTMENTS.register("slow_heavy_blow", SlowHeavyBlowEnchantment::new);//缓慢重击
    public static final RegistryObject<Enchantment> SLOW_HEAVY_WEAKNESS = ENCHANTMENTS.register("slow_heavy_weakness", SlowHeavyWeaknessEnchantment::new);//缓重弱点
    public static final RegistryObject<Enchantment> SPRINT_FIST = ENCHANTMENTS.register("sprint_fist", SprintFistEnchantment::new);//冲刺拳甲
    public static final RegistryObject<Enchantment> TENDON_FIST = ENCHANTMENTS.register("tendon_fist", TendonFistEnchantment::new);//断筋拳甲
    public static final RegistryObject<Enchantment> WEAK_HEAVY_INJURY = ENCHANTMENTS.register("weak_heavy_injury", WeakHeavyInjuryEnchantment::new);//虚弱重伤
    public static final RegistryObject<Enchantment> WEAK_TRAUMA = ENCHANTMENTS.register("weak_trauma", WeakTraumaEnchantment::new);//虚弱创伤
    public static final RegistryObject<Enchantment> REACH_PUNCH_CHESTPLATE = ENCHANTMENTS.register("reach_punch_chestplate", ReachPunchChestplateEnchantment::new);//直延拳甲
    public static final RegistryObject<Enchantment> OVERWORLD_CURSE = ENCHANTMENTS.register("overworld_curse", OverworldCurseEnchantment::new);//主界诅咒
    public static final RegistryObject<Enchantment> LEAP_FORCE = ENCHANTMENTS.register("leap_force", LeapForceEnchantment::new);//跃力
    public static final RegistryObject<Enchantment> PRIMITIVE_LEAP_FORCE = ENCHANTMENTS.register("primitive_leap_force", PrimitiveLeapForceEnchantment::new);//初级跃力
    public static final RegistryObject<Enchantment> CURSED_BLADE = ENCHANTMENTS.register("cursed_blade", CursedBladeEnchantment::new);//诅咒之刃
    public static final RegistryObject<Enchantment> EARTHBOUND = ENCHANTMENTS.register("earthbound", EarthboundEnchantment::new);//地缚
    public static final RegistryObject<Enchantment> FEAR = ENCHANTMENTS.register("fear", FearEnchantment::new);//恐惧
    public static final RegistryObject<Enchantment> GLUTTONOUS_POUCH = ENCHANTMENTS.register("gluttonous_pouch", GluttonousPouchEnchantment::new);//大胃袋
    public static final RegistryObject<Enchantment> INNER_FEAR = ENCHANTMENTS.register("inner_fear", InnerFearEnchantment::new);//内心恐惧
    public static final RegistryObject<Enchantment> LIGHTWEIGHT = ENCHANTMENTS.register("lightweight", LightweightEnchantment::new);//轻盈
    public static final RegistryObject<Enchantment> MASSACRE = ENCHANTMENTS.register("massacre", MassacreEnchantment::new);//群戮
    public static final RegistryObject<Enchantment> SOLO_COMBAT = ENCHANTMENTS.register("solo_combat", SoloCombatEnchantment::new);//独斗
    public static final RegistryObject<Enchantment> METEORITE_STOMP = ENCHANTMENTS.register("meteorite_stomp", MeteoriteStompEnchantment::new);//陨铁踏
    public static final RegistryObject<Enchantment> PAIN_FEAST = ENCHANTMENTS.register("pain_feast", PainFeastEnchantment::new);//噬痛
    public static final RegistryObject<Enchantment> PRIMITIVE_LIGHTWEIGHT = ENCHANTMENTS.register("primitive_lightweight", PrimitiveLightweightEnchantment::new);//初级轻盈
    public static final RegistryObject<Enchantment> PRIMITIVE_MENDING = ENCHANTMENTS.register("primitive_mending", PrimitiveMendingEnchantment::new);//初级经验修补
    public static final RegistryObject<Enchantment> REACH_EXTENSION = ENCHANTMENTS.register("reach_extension", ReachExtensionEnchantment::new);//延申
    public static final RegistryObject<Enchantment> SHARPENED_SHARPNESS = ENCHANTMENTS.register("sharpened_sharpness", SharpenedSharpnessEnchantment::new);//强化锋利
    public static final RegistryObject<Enchantment> SHORT_BREATH = ENCHANTMENTS.register("short_breath", ShortBreathEnchantment::new);//气短
    public static final RegistryObject<Enchantment> SHORT_DIMENSION = ENCHANTMENTS.register("short_dimension", ShortDimensionEnchantment::new);//短寸
    public static final RegistryObject<Enchantment> SIMPLE_BLOCK = ENCHANTMENTS.register("simple_block", SimpleBlockEnchantment::new);//格挡
    public static final RegistryObject<Enchantment> SLOWNESS = ENCHANTMENTS.register("slowness", SlownessEnchantment::new);//迟缓
    public static final RegistryObject<Enchantment> SOULBOUND = ENCHANTMENTS.register("soulbound", SoulboundEnchantment::new);//灵魂持有
    public static final RegistryObject<Enchantment> STOMACH_POUCH = ENCHANTMENTS.register("stomach_pouch", StomachPouchEnchantment::new);//胃袋
    public static final RegistryObject<Enchantment> SWEEPING_BURN_SLASH = ENCHANTMENTS.register("sweeping_burn_slash", SweepingBurnSlashEnchantment::new);//炽魂横扫
    public static final RegistryObject<Enchantment> SWEEPING_ENHANCEMENT = ENCHANTMENTS.register("sweeping_enhancement", SweepingEnhancementEnchantment::new);//强化横扫
    public static final RegistryObject<Enchantment> SWEEPING_FIRE = ENCHANTMENTS.register("sweeping_fire", SweepingFireEnchantment::new);//火之横扫
    public static final RegistryObject<Enchantment> SWEEPING_SLASH = ENCHANTMENTS.register("sweeping_slash", SweepingSlashEnchantment::new);//歼斩横扫
    public static final RegistryObject<Enchantment> SWEEPING_STRIKE = ENCHANTMENTS.register("sweeping_strike", SweepingStrikeEnchantment::new);//横扫打击
    public static final RegistryObject<Enchantment> SWIFT_FEAST = ENCHANTMENTS.register("swift_feast", SwiftFeastEnchantment::new);//速食
    public static final RegistryObject<Enchantment> SWIFT_IMPACT = ENCHANTMENTS.register("swift_impact", SwiftImpactEnchantment::new);//急速冲击
    public static final RegistryObject<Enchantment> SWIFT_STRIKE = ENCHANTMENTS.register("swift_strike", SwiftStrikeEnchantment::new);//速击
    public static final RegistryObject<Enchantment> ULTRA_EDGE = ENCHANTMENTS.register("ultra_edge", UltraEdgeEnchantment::new);//极锋
    public static final RegistryObject<Enchantment> WASPISH = ENCHANTMENTS.register("waspish", WaspishEnchantment::new);//蛰袭之嫌
    public static final RegistryObject<Enchantment> WITHER_BLADE = ENCHANTMENTS.register("wither_blade", WitherBladeEnchantment::new);//凋零锏
    public static final RegistryObject<Enchantment> WITHER_EDGE = ENCHANTMENTS.register("wither_edge", WitherEdgeEnchantment::new);//凋零刃
    public static final RegistryObject<Enchantment> ADVANCED_TIME_AXIS_MENDING = ENCHANTMENTS.register("advanced_time_axis_mending", AdvancedTimeAxisMendingEnchantment::new);//高级时轴修补
    public static final RegistryObject<Enchantment> TIME_AXIS_MENDING = ENCHANTMENTS.register("time_axis_mending", TimeAxisMendingEnchantment::new);//时轴修补
    public static final RegistryObject<Enchantment> PRIMITIVE_TIME_AXIS_MENDING = ENCHANTMENTS.register("primitive_time_axis_mending", PrimitiveTimeAxisMendingEnchantment::new);//初级时轴修补
    public static final RegistryObject<Enchantment> HIGH_STEP = ENCHANTMENTS.register("high_step", HighStepEnchantment::new);//高跨
    public static final RegistryObject<Enchantment> SHADOW_WALKER = ENCHANTMENTS.register("shadow_walker", ShadowWalkerEnchantment::new);//暗影行者
    public static final RegistryObject<Enchantment> CLOUD_WALKER = ENCHANTMENTS.register("cloud_walker", CloudWalkerEnchantment::new);//踏云
    public static final RegistryObject<Enchantment> LOW_DAMAGE_CRITICAL = ENCHANTMENTS.register("low_damage_critical", LowDamageCriticalEnchantment::new);//低伤暴击
    public static final RegistryObject<Enchantment> CRITICAL_OVERCLOCK = ENCHANTMENTS.register("critical_overclock", CriticalOverclockEnchantment::new);//超频暴击
    public static final RegistryObject<Enchantment> DAMAGE_CRITICAL = ENCHANTMENTS.register("damage_critical", DamageCriticalEnchantment::new);//普伤暴击
    public static final RegistryObject<Enchantment> FOCUSED_CRITICAL = ENCHANTMENTS.register("focused_critical", FocusedCriticalEnchantment::new);//专注暴击
    public static final RegistryObject<Enchantment> BASIC_CRITICAL = ENCHANTMENTS.register("basic_critical", BasicCriticalEnchantment::new);//低暴击率
    public static final RegistryObject<Enchantment> CRITICAL_CHANCE = ENCHANTMENTS.register("critical_chance", CriticalChanceEnchantment::new);//暴击率
    public static final RegistryObject<Enchantment> UNDEAD_CURSE = ENCHANTMENTS.register("undead_curse", UndeadCurseEnchantment::new);//亡灵诅咒
    public static final RegistryObject<Enchantment> BLAZING_WAR = ENCHANTMENTS.register("blazing_war", BlazingWarEnchantment::new);//焃战
    public static final RegistryObject<Enchantment> INFERNAL_ARMOR = ENCHANTMENTS.register("infernal_armor", InfernalArmorEnchantment::new);//焚斥之心
    public static final RegistryObject<Enchantment> INFERNAL_REBIRTH = ENCHANTMENTS.register("infernal_rebirth", InfernalRebirthEnchantment::new);//炙浴
    public static final RegistryObject<Enchantment> FIRE_PROTECTION = ENCHANTMENTS.register("fire_protection", FireProtectionEnchantment::new);//焚火庇护
    public static final RegistryObject<Enchantment> FIRE_DEVOUR = ENCHANTMENTS.register("fire_devour", FireDevourEnchantment::new);//火噬
    public static final RegistryObject<Enchantment> BURNING_HEART = ENCHANTMENTS.register("burning_heart", BurningHeartEnchantment::new);//焚心
    public static final RegistryObject<Enchantment> FLAME_SHELL = ENCHANTMENTS.register("flame_shell", FlameShellEnchantment::new);//炎壳
    public static final RegistryObject<Enchantment> BURNING_FURY = ENCHANTMENTS.register("burning_fury", BurningFuryEnchantment::new);//焚怒
    public static final RegistryObject<Enchantment> DESIRE_FLAME = ENCHANTMENTS.register("desire_flame", DesireFlameEnchantment::new);//欲火神修
    public static final RegistryObject<Enchantment> SWIFT_STEP = ENCHANTMENTS.register("swift_step", SwiftStepEnchantment::new);//速行
    public static final RegistryObject<Enchantment> BASIC_SPEED = ENCHANTMENTS.register("basic_speed", BasicSpeedEnchantment::new);//初级速行
    public static final RegistryObject<Enchantment> BITE = ENCHANTMENTS.register("bite", BiteEnchantment::new);//啃食
    public static final RegistryObject<Enchantment> BLESSING_NO24 = ENCHANTMENTS.register("blessing_no24", BlessingNo24Enchantment::new);//24号祝福
    public static final RegistryObject<Enchantment> BLOOD_EDGE = ENCHANTMENTS.register("blood_edge", BloodEdgeEnchantment::new);//饮血棱
    public static final RegistryObject<Enchantment> BLOOD_PACT = ENCHANTMENTS.register("blood_pact", BloodPactEnchantment::new);//血契
    public static final RegistryObject<Enchantment> BLOODTHIRSTY = ENCHANTMENTS.register("bloodthirsty", BloodthirstyEnchantment::new);//嗜血
    public static final RegistryObject<Enchantment> BLOOD_TRANSFUSION = ENCHANTMENTS.register("blood_transfusion", BloodTransfusionEnchantment::new);//输血
    public static final RegistryObject<Enchantment> BLUNT_CRUSHING = ENCHANTMENTS.register("blunt_crushing", BluntCrushingEnchantment::new);//钝碾
    public static final RegistryObject<Enchantment> CHEST_TIGHTNESS = ENCHANTMENTS.register("chest_tightness", ChestTightnessEnchantment::new);//胸闷
    public static final RegistryObject<Enchantment> COMMANDER = ENCHANTMENTS.register("commander", CommanderEnchantment::new);//统领
    public static final RegistryObject<Enchantment> CRUELTY = ENCHANTMENTS.register("cruelty", CrueltyEnchantment::new);//残忍
    public static final RegistryObject<Enchantment> DECAPITATION = ENCHANTMENTS.register("decapitation", DecapitationEnchantment::new);//斩首
    public static final RegistryObject<Enchantment> END_CURSE = ENCHANTMENTS.register("end_curse", EndCurseEnchantment::new);//末地诅咒
    public static final RegistryObject<Enchantment> FRACTURE = ENCHANTMENTS.register("fracture", FractureEnchantment::new);//骨折
    public static final RegistryObject<Enchantment> GENERAL = ENCHANTMENTS.register("general", GeneralEnchantment::new);//将军
    public static final RegistryObject<Enchantment> LEADER = ENCHANTMENTS.register("leader", LeaderEnchantment::new);//领袖
    public static final RegistryObject<Enchantment> LONE_WOLF = ENCHANTMENTS.register("lone_wolf", LoneWolfEnchantment::new);//独狼
    public static final RegistryObject<Enchantment> NETHER_CURSE = ENCHANTMENTS.register("nether_curse", NetherCurseEnchantment::new);//下界诅咒
    public static final RegistryObject<Enchantment> POISON_FANG = ENCHANTMENTS.register("poison_fang", PoisonFangEnchantment::new);//毒牙
    public static final RegistryObject<Enchantment> SENSE = ENCHANTMENTS.register("sense", SenseEnchantment::new);//感知
    public static final RegistryObject<Enchantment> SHARP_EDGE = ENCHANTMENTS.register("sharp_edge", SharpEdgeEnchantment::new);//锋刃
    public static final RegistryObject<Enchantment> SHOVEL_ARMOR_PRIZE = ENCHANTMENTS.register("shovel_armor_prize", ShovelArmorPrizeEnchantment::new);//翘甲
    public static final RegistryObject<Enchantment> SHOVEL_HEAVY_BLOW = ENCHANTMENTS.register("shovel_heavy_blow", ShovelHeavyBlowEnchantment::new);//铲重击
    public static final RegistryObject<Enchantment> SHOVEL_STRIKE = ENCHANTMENTS.register("shovel_strike", ShovelStrikeEnchantment::new);//铲刃
    public static final RegistryObject<Enchantment> SHOVEL_TRIDENT = ENCHANTMENTS.register("shovel_trident", ShovelTridentEnchantment::new);//铲戟
    public static final RegistryObject<Enchantment> ARMOR_PIERCING = ENCHANTMENTS.register("armor_piercing", ArmorPiercingEnchantment::new);//锥心
    public static final RegistryObject<Enchantment> ARMOR_BREAK = ENCHANTMENTS.register("armor_break", ArmorBreakEnchantment::new);//破铠
    public static final RegistryObject<Enchantment> FLINT_STRIKE = ENCHANTMENTS.register("flint_strike", FlintStrikeEnchantment::new);//燧击
    public static final RegistryObject<Enchantment> SICKLE_SLASH = ENCHANTMENTS.register("sickle_slash", SickleSlashEnchantment::new);//镰斩
    public static final RegistryObject<Enchantment> SICKLE_WOUND = ENCHANTMENTS.register("sickle_wound", SickleWoundEnchantment::new);//镰伤
    public static final RegistryObject<Enchantment> KING = ENCHANTMENTS.register("king", KingEnchantment::new);//国王
    public static final RegistryObject<Enchantment> FAST_FALL = ENCHANTMENTS.register("fast_fall", FastFallEnchantment::new);//急坠急停
    public static final RegistryObject<Enchantment> CRASH_LANDING = ENCHANTMENTS.register("crash_landing", CrashLandingEnchantment::new);//坠机
    public static final RegistryObject<Enchantment> POISON_SCAR = ENCHANTMENTS.register("poison_scar", PoisonScarEnchantment::new);//毒痕
    public static final RegistryObject<Enchantment> LAVA_WALKER = ENCHANTMENTS.register("lava_walker", LavaWalkerEnchantment::new);//熔岩行者
    public static final RegistryObject<Enchantment> FOOD_POWER_STRIKE = ENCHANTMENTS.register("food_power_strike", FoodPowerStrikeEnchantment::new);//食力斩
    public static final RegistryObject<Enchantment> LIFE_BLOCK = ENCHANTMENTS.register("life_block", LifeBlockEnchantment::new);//生命格挡
    public static final RegistryObject<Enchantment> PRIEST_BLESSING = ENCHANTMENTS.register("priest_blessing", PriestBlessingEnchantment::new);//牧师祝福
    public static final RegistryObject<Enchantment> THUNDER_RETRIBUTION = ENCHANTMENTS.register("thunder_retribution", ThunderRetributionEnchantment::new);//雷劫
    public static final RegistryObject<Enchantment> KNIGHT = ENCHANTMENTS.register("knight", KnightEnchantment::new);//骑士
    public static final RegistryObject<Enchantment> OCEAN_BLESSING = ENCHANTMENTS.register("ocean_blessing", OceanBlessingEnchantment::new);//海洋庇佑
    public static final RegistryObject<Enchantment> HEADHUNTER = ENCHANTMENTS.register("headhunter", HeadhunterEnchantment::new);//弑魁
    public static final RegistryObject<Enchantment> HOLD_BREATH = ENCHANTMENTS.register("hold_breath", HoldBreathEnchantment::new);//闭气
    public static final RegistryObject<Enchantment> IRON_LUNG = ENCHANTMENTS.register("iron_lung", IronLungEnchantment::new);//铁肺
    public static final RegistryObject<Enchantment> HIGH_ALTITUDE_OXYGEN_DEFICIENCY = ENCHANTMENTS.register("high_altitude_oxygen_deficiency", HighAltitudeOxygenDeficiencyEnchantment::new);//高原缺氧
    public static final RegistryObject<Enchantment> OXYGEN_DEPLETING_SPRINT = ENCHANTMENTS.register("oxygen_depleting_sprint", OxygenDepletingSprintEnchantment::new);//耗氧冲刺
    public static final RegistryObject<Enchantment> BREATH_HEAL = ENCHANTMENTS.register("breath_heal", BreathHealEnchantment::new);//呼吸治疗
    public static final RegistryObject<Enchantment> HYPOXIA_SPRINT = ENCHANTMENTS.register("hypoxia_sprint", HypoxiaSprintEnchantment::new);//低氧冲刺
    public static final RegistryObject<Enchantment> DEEP_PRESSURE = ENCHANTMENTS.register("deep_pressure", DeepPressureEnchantment::new);//深压
    public static final RegistryObject<Enchantment> WOUND_RIFT = ENCHANTMENTS.register("wound_rift", WoundRiftEnchantment::new);//伤裂
    public static final RegistryObject<Enchantment> MAIM = ENCHANTMENTS.register("maim", MaimEnchantment::new);//伤残
    public static final RegistryObject<Enchantment> ARMOR_DAMAGE = ENCHANTMENTS.register("armor_damage", ArmorDamageEnchantment::new);//盔损
    public static final RegistryObject<Enchantment> STEALTH_HUNTER = ENCHANTMENTS.register("stealth_hunter", StealthHunterEnchantment::new);//匿猎
    public static final RegistryObject<Enchantment> ARMOR_SHATTER = ENCHANTMENTS.register("armor_shatter", ArmorShatterEnchantment::new);//盔碎
    public static final RegistryObject<Enchantment> EXPERIENCE_HARVEST = ENCHANTMENTS.register("experience_harvest", ExperienceHarvestEnchantment::new);//经验收割
    public static final RegistryObject<Enchantment> CROP_HARVEST = ENCHANTMENTS.register("crop_harvest", CropHarvestEnchantment::new);//超额丰收
    public static final RegistryObject<Enchantment> DROP_REAPER = ENCHANTMENTS.register("drop_reaper", DropReaperEnchantment::new);//掉落收割
    public static final RegistryObject<Enchantment> RAIN_NOURISHMENT = ENCHANTMENTS.register("rain_nourishment", RainNourishmentEnchantment::new);//雨露滋养
    public static final RegistryObject<Enchantment> FOOT_BLOCK = ENCHANTMENTS.register("foot_block", FootBlockEnchantment::new);//脚部搭建
    public static final RegistryObject<Enchantment> RANGE_FOOT_BLOCK = ENCHANTMENTS.register("range_foot_block", RangeFootBlockEnchantment::new);//范围脚部搭建
    public static final RegistryObject<Enchantment> TILLAGE_BOOT = ENCHANTMENTS.register("tillage_boot", TillageBootEnchantment::new);//耕耘锄
    public static final RegistryObject<Enchantment> WEED_REMOVAL_BOOT = ENCHANTMENTS.register("weed_removal_boot", WeedRemovalBootEnchantment::new);//除草锄
    public static final RegistryObject<Enchantment> SNOW_REMOVAL_BOOT = ENCHANTMENTS.register("snow_removal_boot", SnowRemovalBootEnchantment::new);//除雪铲
    public static final RegistryObject<Enchantment> PANIC_ESCAPE = ENCHANTMENTS.register("panic_escape", PanicEscapeEnchantment::new);//恐慌逃离
    public static final RegistryObject<Enchantment> DESPERATE_ESCAPE = ENCHANTMENTS.register("desperate_escape", DesperateEscapeEnchantment::new);//绝境逃离
    public static final RegistryObject<Enchantment> DESPERATE_KILL = ENCHANTMENTS.register("desperate_kill", DesperateKillEnchantment::new);//绝境杀戮
    public static final RegistryObject<Enchantment> DESPERATE_RESILIENCE = ENCHANTMENTS.register("desperate_resilience", DesperateResilienceEnchantment::new);//绝境坚韧
    public static final RegistryObject<Enchantment> EXECUTE_RATE = ENCHANTMENTS.register("execute_rate", ExecuteRateEnchantment::new);//斩杀率
    public static final RegistryObject<Enchantment> EXECUTE_POWER = ENCHANTMENTS.register("execute_power", ExecutePowerEnchantment::new);//斩杀力
    public static final RegistryObject<Enchantment> FOCUSED_AMBUSH = ENCHANTMENTS.register("focused_ambush", FocusedAmbushEnchantment::new);//专注伏击
    public static final RegistryObject<Enchantment> KILLING_SENSE = ENCHANTMENTS.register("killing_sense", KillingSenseEnchantment::new);//杀戮感知
    public static final RegistryObject<Enchantment> BURNING_TRAUMA = ENCHANTMENTS.register("burning_trauma", BurningTraumaEnchantment::new);//烈火创伤
    public static final RegistryObject<Enchantment> DUAL_WIELD = ENCHANTMENTS.register("dual_wield", DualWieldEnchantment::new);//无双
    public static final RegistryObject<Enchantment> HEARTBEAT_RHYTHM = ENCHANTMENTS.register("heartbeat_rhythm", HeartbeatRhythmEnchantment::new);//心动律动
    public static final RegistryObject<Enchantment> HABITAT = ENCHANTMENTS.register("habitat", HabitatEnchantment::new);//栖所
    public static final RegistryObject<Enchantment> CAMPFIRE_HEAL = ENCHANTMENTS.register("campfire_heal", CampfireHealEnchantment::new);//篝愈
    public static final RegistryObject<Enchantment> MARTIAL_RHYTHM = ENCHANTMENTS.register("martial_rhythm", MartialRhythmEnchantment::new);//武道律动
    public static final RegistryObject<Enchantment> NETHER_CORROSION = ENCHANTMENTS.register("nether_corrosion", NetherCorrosionEnchantment::new);//下届腐蚀
    public static final RegistryObject<Enchantment> END_CORROSION = ENCHANTMENTS.register("end_corrosion", EndCorrosionEnchantment::new);//末地腐蚀
    public static final RegistryObject<Enchantment> OVERWORLD_CORROSION = ENCHANTMENTS.register("overworld_corrosion", OverworldCorrosionEnchantment::new);//主界腐蚀
    public static final RegistryObject<Enchantment> EXHAUSTION = ENCHANTMENTS.register("exhaustion", ExhaustionEnchantment::new);//力竭
    public static final RegistryObject<Enchantment> SIGHING_STRIKE = ENCHANTMENTS.register("sighing_strike", SighingStrikeEnchantment::new);//力叹斩
    public static final RegistryObject<Enchantment> UNDEAD_COMMANDER = ENCHANTMENTS.register("undead_commander", UndeadCommanderEnchantment::new);//亡灵统帅
    public static final RegistryObject<Enchantment> ILLAGER_COMMANDER = ENCHANTMENTS.register("illager_commander", IllagerCommanderEnchantment::new);//灾厄统领
    public static final RegistryObject<Enchantment> STRONG_THORNS = ENCHANTMENTS.register("strong_thorns", StrongThornsEnchantment::new);//强力反伤
    public static final RegistryObject<Enchantment> SOUL_REPULSION = ENCHANTMENTS.register("soul_repulsion", SoulRepulsionEnchantment::new);//斥魂爆震
    public static final RegistryObject<Enchantment> PLUNDER_WEALTH = ENCHANTMENTS.register("plunder_wealth", PlunderWealthEnchantment::new);//掠财
    public static final RegistryObject<Enchantment> LOOT_ATTRACTION = ENCHANTMENTS.register("loot_attraction", LootAttractionEnchantment::new);//掉落吸引
    public static final RegistryObject<Enchantment> STINKY_FEET = ENCHANTMENTS.register("stinky_feet", StinkyFeetEnchantment::new);//脚臭
    public static final RegistryObject<Enchantment> SUPER_STINKY_FEET = ENCHANTMENTS.register("super_stinky_feet", SuperStinkyFeetEnchantment::new);//超级脚臭
    public static final RegistryObject<Enchantment> SHIELD_SHOCK = ENCHANTMENTS.register("shield_shock", ShieldShockEnchantment::new);//盾震
    public static final RegistryObject<Enchantment> HATRED_TAUNT = ENCHANTMENTS.register("hatred_taunt", HatredTauntEnchantment::new);//仇引
    public static final RegistryObject<Enchantment> HOVER = ENCHANTMENTS.register("hover", HoverEnchantment::new);//氧力悬停
    public static final RegistryObject<Enchantment> TAUNT_EXCITEMENT = ENCHANTMENTS.register("taunt_excitement", TauntExcitementEnchantment::new);//诱敌兴奋
    public static final RegistryObject<Enchantment> NOISY_SOUND = ENCHANTMENTS.register("noisy_sound", NoisySoundEnchantment::new);//音躁
    public static final RegistryObject<Enchantment> SOUL_REAPING_SICKLE = ENCHANTMENTS.register("soul_reaping_sickle", SoulReapingSickleEnchantment::new);//祭魂镰斩
    public static final RegistryObject<Enchantment> SOUL_PAYING_CUT = ENCHANTMENTS.register("soul_paying_cut", SoulPayingCutEnchantment::new);//付魂斩
    public static final RegistryObject<Enchantment> MILITARY_SHOVEL = ENCHANTMENTS.register("military_shovel", MilitaryShovelEnchantment::new);//功能军锹
    public static final RegistryObject<Enchantment> UNIVERSAL_SHOVEL = ENCHANTMENTS.register("universal_shovel", UniversalShovelEnchantment::new);//万能军锹
    public static final RegistryObject<Enchantment> VITALITY_BOOST = ENCHANTMENTS.register("vitality_boost", VitalityBoostEnchantment::new);// 肉铠
    public static final RegistryObject<Enchantment> EXERCISE = ENCHANTMENTS.register("exercise", ExerciseEnchantment::new);// 锻炼
    public static final RegistryObject<Enchantment> GLUTTONY = ENCHANTMENTS.register("gluttony", GluttonyEnchantment::new);// 饕餮
    public static final RegistryObject<Enchantment> STURDY_BARBARIAN = ENCHANTMENTS.register("sturdy_barbarian", SturdyBarbarianEnchantment::new);// 磐蛮
    public static final RegistryObject<Enchantment> STEEL_BODY = ENCHANTMENTS.register("steel_body", SteelBodyEnchantment::new);// 钢躯
    public static final RegistryObject<Enchantment> OBESITY = ENCHANTMENTS.register("obesity", ObesityEnchantment::new);// 肥硕
    public static final RegistryObject<Enchantment> TIME_AXIS_DECAY = ENCHANTMENTS.register("time_axis_decay", TimeAxisDecayEnchantment::new);// 时轴损毁
    public static final RegistryObject<Enchantment> MANUAL_ROUGH_REPAIR = ENCHANTMENTS.register("manual_rough_repair", ManualRoughRepairEnchantment::new);// 手动粗修
    public static final RegistryObject<Enchantment> MANUAL_FINE_REPAIR = ENCHANTMENTS.register("manual_fine_repair", ManualFineRepairEnchantment::new);// 手动精修
    public static final RegistryObject<Enchantment> BATTLE_HARDENED = ENCHANTMENTS.register("battle_hardened", BattleHardenedEnchantment::new);// 久经沙场
    public static final RegistryObject<Enchantment> BATTLE_SCARRED = ENCHANTMENTS.register("battle_scarred", BattleScarredEnchantment::new);// 战痕累累
    public static final RegistryObject<Enchantment> PROMISING_BLADE = ENCHANTMENTS.register("promising_blade", PromisingBladeEnchantment::new);// 初露锋芒
    public static final RegistryObject<Enchantment> MIGHTY_STRIKE = ENCHANTMENTS.register("mighty_strike", MightyStrikeEnchantment::new);// 力量突效
    public static final RegistryObject<Enchantment> HASTE_SURGE = ENCHANTMENTS.register("haste_surge", HasteSurgeEnchantment::new);// 急迫突效
    public static final RegistryObject<Enchantment> RESISTANCE_SURGE = ENCHANTMENTS.register("resistance_surge", ResistanceSurgeEnchantment::new);// 抗性突效
    public static final RegistryObject<Enchantment> MIGHTY_CONTINUATION = ENCHANTMENTS.register("mighty_continuation", MightyContinuationEnchantment::new);// 力量续效
    public static final RegistryObject<Enchantment> HASTE_CONTINUATION = ENCHANTMENTS.register("haste_continuation", HasteContinuationEnchantment::new);// 急迫续效
    public static final RegistryObject<Enchantment> RESISTANCE_CONTINUATION = ENCHANTMENTS.register("resistance_continuation", ResistanceContinuationEnchantment::new);// 抗性续效
    public static final RegistryObject<Enchantment> FOCUSED_STEADINESS = ENCHANTMENTS.register("focused_steadiness", FocusedSteadinessEnchantment::new);// 专注稳重
    public static final RegistryObject<Enchantment> NIGHT_VISION = ENCHANTMENTS.register("night_vision", NightVisionEnchantment::new);// 夜朦
    public static final RegistryObject<Enchantment> STAGGERING_BLOW = ENCHANTMENTS.register("staggering_blow", StaggeringBlowEnchantment::new);// 顿挫
    public static final RegistryObject<Enchantment> DANGEROUS_AURA = ENCHANTMENTS.register("dangerous_aura", DangerousAuraEnchantment::new);// 惧慑
    public static final RegistryObject<Enchantment> CORE_COLLECTION = ENCHANTMENTS.register("core_collection", CoreCollectionEnchantment::new);// 核心采集
    public static final RegistryObject<Enchantment> BODY_SNATCH = ENCHANTMENTS.register("body_snatch", BodySnatchEnchantment::new);//摄魂镰
    public static final RegistryObject<Enchantment> HEART_OF_TIDE = ENCHANTMENTS.register("heart_of_tide", HeartOfTideEnchantment::new);// 潮涌之心
    public static final RegistryObject<Enchantment> WHISPER = ENCHANTMENTS.register("whisper", WhisperEnchantment::new);// 轻语
    public static final RegistryObject<Enchantment> HEART_OF_FLINT = ENCHANTMENTS.register("heart_of_flint", HeartOfFlintEnchantment::new);// 燧心
    public static final RegistryObject<Enchantment> SOUL_ARROW = ENCHANTMENTS.register("soul_arrow", SoulArrowEnchantment::new);// 游魂矢
    public static final RegistryObject<Enchantment> WILDFIRE_ARROW = ENCHANTMENTS.register("wildfire_arrow", WildfireArrowEnchantment::new);// 燎原矢
    public static final RegistryObject<Enchantment> DRAGON_BREATH_ARROW = ENCHANTMENTS.register("dragon_breath_arrow", DragonBreathArrowEnchantment::new);// 龙息矢
    public static final RegistryObject<Enchantment> REPEATING_BOLT = ENCHANTMENTS.register("repeating_bolt", RepeatingBoltEnchantment::new);// 重程弩
    public static final RegistryObject<Enchantment> WATER_ARROW = ENCHANTMENTS.register("water_arrow", WaterArrowEnchantment::new);// 水矢
    public static final RegistryObject<Enchantment> DROUGHT_ARROW = ENCHANTMENTS.register("drought_arrow", DroughtArrowEnchantment::new);// 干矢
    public static final RegistryObject<Enchantment> WEAKNESS = ENCHANTMENTS.register("weakness", WeaknessEnchantment::new);// 力弱
    public static final RegistryObject<Enchantment> SNAP_STRING = ENCHANTMENTS.register("snap_string", SnapStringEnchantment::new);// 断弦
    public static final RegistryObject<Enchantment> BOUNCE = ENCHANTMENTS.register("bounce", BounceEnchantment::new);// 弹射
    public static final RegistryObject<Enchantment> RANGER = ENCHANTMENTS.register("ranger", RangerEnchantment::new);// 游侠
    public static final RegistryObject<Enchantment> STEADY_SHOT = ENCHANTMENTS.register("steady_shot", SteadyShotEnchantment::new);// 磐射
    public static final RegistryObject<Enchantment> ENEMY_TAUNT = ENCHANTMENTS.register("enemy_taunt", EnemyTauntEnchantment::new);// 敌引
    public static final RegistryObject<Enchantment> PIERCING = ENCHANTMENTS.register("piercing", PiercingEnchantment::new);// 穿体
    public static final RegistryObject<Enchantment> VETERAN = ENCHANTMENTS.register("veteran", VeteranEnchantment::new);//身经百战
    public static final RegistryObject<Enchantment> PEREGRINE = ENCHANTMENTS.register("peregrine", PeregrineEnchantment::new);// 游隼
    public static final RegistryObject<Enchantment> HEART_OF_DROUGHT = ENCHANTMENTS.register("heart_of_drought", HeartOfDroughtEnchantment::new);//干渴之心
    public static final RegistryObject<Enchantment> HEAVY_IMPACT = ENCHANTMENTS.register("heavy_impact", HeavyImpactEnchantment::new);// 沉击
    public static final RegistryObject<Enchantment> TELEPORT_ARROW = ENCHANTMENTS.register("teleport_arrow", TeleportArrowEnchantment::new);// 传送箭
    public static final RegistryObject<Enchantment> SWAP_TELEPORT = ENCHANTMENTS.register("swap_teleport", SwapTeleportEnchantment::new);// 置换矢
    public static final RegistryObject<Enchantment> TOY_BOW = ENCHANTMENTS.register("toy_bow", ToyBowEnchantment::new);// 玩具
    public static final RegistryObject<Enchantment> POINT_SHOOT = ENCHANTMENTS.register("point_shoot", PointShootEnchantment::new);// 点射
    public static final RegistryObject<Enchantment> RECYCLE = ENCHANTMENTS.register("recycle", RecycleEnchantment::new);// 回收
    public static final RegistryObject<Enchantment> TRANSFER = ENCHANTMENTS.register("transfer", TransferEnchantment::new);// 传输
    public static final RegistryObject<Enchantment> ARMY_SUMMON = ENCHANTMENTS.register("army_summon", ArmySummonEnchantment::new);// 召军
    public static final RegistryObject<Enchantment> ELYTRA_ARMOR = ENCHANTMENTS.register("elytra_armor", ElytraArmorEnchantment::new);// 翅韧战甲
}